spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/AppStore
    username: postgres
    password: pgadmin
  jpa:
    show-sql: false
    hibernate:
     ddl-auto: create
