alter table if exists address
    drop constraint if exists FK8bvxvrrqxhjo4cj00poy9mvq3;
alter table if exists basket
    drop constraint if exists FKtfkg0nrdij056rk1uap5ai9af;
alter table if exists basket
    drop constraint if exists FKpdd1bi5fn0u8ed9hmprhw6d5m;
alter table if exists order_entity
    drop constraint if exists FK8lvfdehnvu69xopspvaoqkik4;
alter table if exists order_entity
    drop constraint if exists FKbycvaqrbh7ihbqv9dhlsh48vn;
alter table if exists order_entity
    drop constraint if exists FKsgn6vd4358jar6ukqngcu9re1;
alter table if exists order_entity_store_item
    drop constraint if exists FKlkh6g1cupl5j0iwaall3r1nj1;
alter table if exists order_entity_store_item
    drop constraint if exists FK612uxjny23l5mo34lrifhhb93;
alter table if exists store_item
    drop constraint if exists FKkus2ahsbquy8e5ji1cu29hwnw;
alter table if exists store_item
    drop constraint if exists FK47xvy7oim2h8wrbxruonb35fw;
drop table if exists address cascade;
drop table if exists basket cascade;
drop table if exists item cascade;
drop table if exists manager cascade;
drop table if exists order_entity cascade;
drop table if exists order_entity_store_item cascade;
drop table if exists store_user cascade;
drop table if exists store_item cascade;
create table address
(
    id       int4 generated by default as identity,
    base     varchar(255),
    city     varchar(255),
    entrance varchar(255),
    flat     varchar(255),
    floor    varchar(255),
    street   varchar(255),
    visible  boolean not null,
    user_id  int4,
    primary key (id)
);
create table basket
(
    id            int4 generated by default as identity,
    count         int8 not null,
    price         numeric(19, 2),
    store_item_id int4,
    user_id       int4,
    primary key (id)
);
create table item
(
    id                   int4 generated by default as identity,
    cpu                  varchar(255),
    available            boolean not null,
    description          varchar(255),
    driver_configuration varchar(255),
    name                 varchar(255),
    release_date         date,
    type                 varchar(255),
    primary key (id)
);
create table manager
(
    id              int4 generated by default as identity,
    deleted         boolean not null,
    password        varchar(255),
    personal_number varchar(255),
    user_name       varchar(255),
    primary key (id)
);
create table order_entity
(
    id                  int4 generated by default as identity,
    date                date,
    date_of_refactoring timestamp,
    external_id         varchar(255),
    price               numeric(19, 2),
    status              varchar(255),
    address_id          int4,
    refactor_by         int4,
    user_id             int4,
    primary key (id)
);
create table order_entity_store_item
(
    order_entity_id int4 not null,
    store_item_id   int4 not null
);
create table store_user
(
    id           int4 generated by default as identity,
    available    boolean not null,
    birthday     date,
    name         varchar(255),
    password     varchar(255),
    phone_number varchar(255),
    surname      varchar(255),
    primary key (id)
);
create table store_item
(
    id          int4 generated by default as identity,
    available   boolean not null,
    price       numeric(19, 2),
    item_id     int4,
    refactor_by int4,
    primary key (id)
);
alter table if exists address
    add constraint FK8bvxvrrqxhjo4cj00poy9mvq3 foreign key (user_id) references store_user;
alter table if exists basket
    add constraint FKtfkg0nrdij056rk1uap5ai9af foreign key (store_item_id) references store_item;
alter table if exists basket
    add constraint FKpdd1bi5fn0u8ed9hmprhw6d5m foreign key (user_id) references store_user;
alter table if exists order_entity
    add constraint FK8lvfdehnvu69xopspvaoqkik4 foreign key (address_id) references address;
alter table if exists order_entity
    add constraint FKbycvaqrbh7ihbqv9dhlsh48vn foreign key (refactor_by) references manager;
alter table if exists order_entity
    add constraint FKsgn6vd4358jar6ukqngcu9re1 foreign key (user_id) references store_user;
alter table if exists order_entity_store_item
    add constraint FKlkh6g1cupl5j0iwaall3r1nj1 foreign key (store_item_id) references store_item;
alter table if exists order_entity_store_item
    add constraint FK612uxjny23l5mo34lrifhhb93 foreign key (order_entity_id) references order_entity;
alter table if exists store_item
    add constraint FKkus2ahsbquy8e5ji1cu29hwnw foreign key (item_id) references item;
alter table if exists store_item
    add constraint FK47xvy7oim2h8wrbxruonb35fw foreign key (refactor_by) references manager